In [ ]:
#default_exp data.datasets.epf

# EPF dataset

> API details.

In [ ]:
#export
from dataclasses import dataclass
from datetime import timedelta
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Union

import numpy as np
import pandas as pd
from pandas.tseries.frequencies import to_offset

from nixtla.data.datasets.utils import download_file, Info, TimeSeriesDataclass
from nixtla.data.ts_dataset import TimeSeriesDataset

In [ ]:
#export
SOURCE_URL = 'https://sandbox.zenodo.org/api/files/da5b2c6f-8418-4550-a7d0-7f2497b40f1b/'

Tourism meta information

In [ ]:
#export
@dataclass
class NP:
    test_date: str = '2016-12-27'
    name: str = 'NP'

@dataclass
class PJM:
    test_date: str = '2016-12-27'
    name: str = 'PJM'

@dataclass
class BE:
    test_date: str = '2015-01-04'
    name: str = 'BE'

@dataclass
class FR:
    test_date: str = '2015-01-04'
    name: str = 'FR'

@dataclass
class DE:
    test_date: str = '2016-01-04'
    name: str = 'DE'

In [ ]:
#export
EPFInfo = Info(groups=('NP', 'PJM', 'BE', 'FR', 'DE'),
               class_groups=(NP, PJM, BE, FR, DE))

In [ ]:
#export
class EPF:

    #@staticmethod
    def load(directory: str,
             group: str,
             training: bool = True,
             days_in_test: int = 728,
             ts_train_mask = None, #TODO: hint
             return_tensor: bool = True): # -> Union[TimeSeriesDataset, TimeSeriesDataclass]
        """
        Downloads and loads EPF data.

        Parameters
        ----------
        directory: str
            Directory where data will be downloaded.
        group: str
            Group name.
            Allowed groups: 'NP', 'PJM', 'BE', 'FR', 'DE'.
        training: bool
            Wheter return training or testing data. Default True.
        days_in_test: int
            Number of days to consider in test.
            Only used when training=True.
        return_tensor: bool
            Wheter return TimeSeriesDataset (tensors, True) or
            TimeSeriesDataclass (dataframes)
        """
        path = Path(directory) / 'epf' / 'datasets'

        EPF.download(directory)

        class_group = EPFInfo.get_group(group)

        file = path / f'{group}.csv'

        df = pd.read_csv(file)

        df.columns = ['ds', 'y'] + \
                     [f'Exogenous{i}' for i in range(1, len(df.columns) - 1)]

        df['unique_id'] = group
        df['ds'] = pd.to_datetime(df['ds'])
        df['week_day'] = df['ds'].dt.dayofweek

        dummies = pd.get_dummies(df['week_day'], prefix='day')
        df = pd.concat([df, dummies], axis=1)

        dummies_cols = [col for col in df \
                        if (col.startswith('day') or col.startswith('hour_'))]

        if training:
            df = df.query('ds < @class_group.test_date')
        else:
            last_date_test = pd.to_datetime(class_group.test_date) + \
                             timedelta(days=days_in_test)
            df = df.query('ds >= @class_group.test_date')

        Y = df.filter(items=['unique_id', 'ds', 'y'])
        X = df.filter(items=['unique_id', 'ds', 'Exogenous1', 'Exogenous2'] + \
                      dummies_cols)
        
    #def get_data(self):
        return Y, X
        # if return_tensor:
        #     return TimeSeriesDataset(y_df=Y, X_s_df=None, X_t_df=X, ts_train_mask=ts_train_mask)
        # else:
        #     return TimeSeriesDataclass(Y=Y, S=None, X=X, group=group)

    @staticmethod
    def load_groups(directory: str,
                    groups: List[str] = ['BE', 'FR'],
                    training: bool = True,
                    days_in_test: int = 728,
                    return_tensor: bool = True) -> Union[TimeSeriesDataset, TimeSeriesDataclass]:
        """
        Downloads and loads panel of EPF data
        according of groups.

        Parameters
        ----------
        directory: str
            Directory where data will be downloaded.
        groups: List[str]
            Group names.
            Allowed groups: 'NP', 'PJM', 'BE', 'FR', 'DE'.
        training: bool
            Wheter return training or testing data. Default True.
        days_in_test: int
            Number of days to consider in test.
            Only used when training=True.
        return_tensor: bool
            Wheter return TimeSeriesDataset (tensors, True) or
            TimeSeriesDataclass (dataframes)
        """
        Y = []
        X = []
        for group in groups:
            data = EPF.load(directory, group,
                            training, days_in_test,
                            return_tensor=False)
            Y.append(data.Y)
            X.append(data.X)
        Y = pd.concat(Y).sort_values(['unique_id', 'ds']).reset_index(drop=True)
        X = pd.concat(X).sort_values(['unique_id', 'ds']).reset_index(drop=True)

        S = Y[['unique_id']].drop_duplicates().reset_index(drop=True)
        dummies = pd.get_dummies(S['unique_id'], prefix='static')
        S = pd.concat([S, dummies], axis=1)
        
        if return_tensor:
            return TimeSeriesDataset(y_df=Y, X_s_df=None, X_t_df=X)
        else:
            return TimeSeriesDataclass(Y=Y, S=S, X=X, group=groups)

    @staticmethod
    def download(directory: str) -> None:
        """Downloads EPF Dataset."""
        path = Path(directory) / 'epf' / 'datasets'
        if not path.exists():
            for group in EPFInfo.groups:
                download_file(path, SOURCE_URL + f'{group}.csv')

## Load specific group

In [ ]:
pjm = EPF.load('data', group='PJM')
pjm_test = EPF.load('data', group='PJM', training=False)

Processing dataframes ...
Creating ts tensor ...
Processing dataframes ...
Creating ts tensor ...


In [ ]:
print('TS tensor: \n', pjm.ts_tensor) 

TS tensor: 
 tensor([[[2.5464e+01, 2.3555e+01, 2.2122e+01,  ..., 2.4525e+01,
          2.2835e+01, 2.0455e+01],
         [8.5049e+04, 8.2128e+04, 8.0729e+04,  ..., 9.3346e+04,
          8.7603e+04, 8.1626e+04],
         [1.1509e+04, 1.0942e+04, 1.0639e+04,  ..., 1.2129e+04,
          1.1642e+04, 1.0924e+04],
         ...,
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [1.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 1.0000e+00,
          1.0000e+00, 1.0000e+00]]])


In [ ]:
print('TS tensor test: \n', pjm_test.ts_tensor) 

TS tensor test: 
 tensor([[[1.9113e+01, 1.8043e+01, 1.7587e+01,  ..., 2.6406e+01,
          2.4647e+01, 2.3980e+01],
         [7.4616e+04, 7.1821e+04, 7.0353e+04,  ..., 9.2923e+04,
          9.0970e+04, 8.8037e+04],
         [1.0214e+04, 9.7020e+03, 9.4310e+03,  ..., 1.0963e+04,
          1.0802e+04, 1.0419e+04],
         ...,
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [1.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 1.0000e+00,
          1.0000e+00, 1.0000e+00]]])


## Load set of groups

In [ ]:
groups = ['PJM', 'NP', 'FR', 'BE', 'DE']
pjm = EPF.load_groups('data', groups=groups)
pjm_test = EPF.load_groups('data', groups=groups)

Processing dataframes ...
Creating ts tensor ...
Processing dataframes ...
Creating ts tensor ...


In [ ]:
print('TS tensor: \n', pjm.ts_tensor) 

TS tensor: 
 tensor([[[3.2540e+01, 2.1550e+01, 1.5710e+01,  ..., 4.2440e+01,
          4.2030e+01, 4.0910e+01],
         [6.3065e+04, 6.2715e+04, 6.1952e+04,  ..., 7.2883e+04,
          7.2926e+04, 7.3070e+04],
         [6.3000e+04, 5.8800e+04, 5.8500e+04,  ..., 6.4515e+04,
          6.2554e+04, 6.7342e+04],
         ...,
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 1.0000e+00,
          1.0000e+00, 1.0000e+00],
         [1.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [1.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 1.0000e+00,
          1.0000e+00, 1.0000e+00]],

        [[3.4970e+01, 3.3430e+01, 3.2740e+01,  ..., 2.2110e+01,
          2.0910e+01, 1.4430e+01],
         [2.0720e+03, 1.9298e+03, 1.8560e+03,  ..., 1.4118e+03,
          1.4292e+03, 1.4318e+03],
         [1.6382e+04, 1.5410e+04, 1.5595e+04,  ..., 1.8490e+04,
          1.8718e+04, 1.7559e+04],
         ...,
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
  

In [ ]:
print('TS tensor test: \n', pjm_test.ts_tensor) 

TS tensor test: 
 tensor([[[3.2540e+01, 2.1550e+01, 1.5710e+01,  ..., 4.2440e+01,
          4.2030e+01, 4.0910e+01],
         [6.3065e+04, 6.2715e+04, 6.1952e+04,  ..., 7.2883e+04,
          7.2926e+04, 7.3070e+04],
         [6.3000e+04, 5.8800e+04, 5.8500e+04,  ..., 6.4515e+04,
          6.2554e+04, 6.7342e+04],
         ...,
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 1.0000e+00,
          1.0000e+00, 1.0000e+00],
         [1.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [1.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 1.0000e+00,
          1.0000e+00, 1.0000e+00]],

        [[3.4970e+01, 3.3430e+01, 3.2740e+01,  ..., 2.2110e+01,
          2.0910e+01, 1.4430e+01],
         [2.0720e+03, 1.9298e+03, 1.8560e+03,  ..., 1.4118e+03,
          1.4292e+03, 1.4318e+03],
         [1.6382e+04, 1.5410e+04, 1.5595e+04,  ..., 1.8490e+04,
          1.8718e+04, 1.7559e+04],
         ...,
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+0